.catalog:
  name: "MongoDB"
  version: "3.2-rancher2"
  description: "MongoDB Replica Set"
  uuid: mongodb-1
  minimum_rancher_version: v0.46.0
  questions:
    - variable: replset_name
      description: "Name of the MongoDB replicaSet"
      label: "ReplicaSet Name"
      type: "string"
      required: true
      default: "rs0"
    - variable: host_label
      label: "Host Label to MongoDB Tags"
      description: |
        Host label to use as MongoDB 'value' tag.
        Example: 'database'
      required: false
      type: "string"
    - variable: debug
      description: "Enable Debug log for Mongo containers"
      label: "Debug"
      type: "string"
      required: false
      default: ""
    - variable: additional_params
      Label: "Additional parameters"
      description: "Additional Parameters to pass to mongod"
      type: string
      required: false
      default: ""
    - variable: mongodb_version
      description: "Version of the MongoDB official container to pull (defaults to 3.2)"
      label: MongoDB Version
      type: string
      required: false
      default: 3.2
    - variable: volume_driver
      label: Volume Driver
      description: "Driver to use for data volumes (defaults to none)"
      type: string
      required: false
      default: "none"
mongo-cluster:
  scale: 3
  retain_ip: true
  metadata:
    mongo:
      yml:
        replset.name: "${replset_name}"
